#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

CLUSTERS="$(
gh api \
  -H "Accept: application/vnd.github+json" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  '/search/repositories?q=gds.clusterconfig.&per_page=100' \
	| jq -r '.items[]|.name' \
	| sort \
  | awk -F'.' -v ORS=$'\t' '/^gds[.]clusterconfig[.][ispj][0-9]{2}/ {print $3}' \
)"

function ensure_wiki() {
  CLUSTER="$1"
  echo "    Replacing Wiki Action in $CLUSTER"
  cp ../tml/generate-wiki-links.yml .github/workflows/generate-wiki-links.yml
  git add .github/workflows/generate-wiki-links.yml
}

function fix_codeowners() {
  CLUSTER="$1"
  # Specify the usernames to remove
  usernames=(
    "igroff"
    "datfinesoul"
    "bkelley123"
    "sayeefb"
    "glg\/github-maintenance-admin"
  )

  # Path to your CODEOWNERS file
  codeowners_file="CODEOWNERS"

  # Read the file into an array
  mapfile -t lines < "$codeowners_file"

  # Loop through the lines and modify the appropriate line
  for ((i=0; i<${#lines[@]}; i++)); do
    line="${lines[$i]}"
    if echo "$line" | grep -q "^\*"; then
      # Remove the usernames from the line
      for username in "${usernames[@]}"; do
        line=$(echo "$line" | sed "s/ @$username//g")
      done
      # Update the line in the array
      lines[$i]="$line"
      break
    fi
  done

  # Write the modified lines back to the file
  printf "%s\n" "${lines[@]}" > "$codeowners_file"
}

for CLUSTER in $CLUSTERS; do
  echo "[+] $CLUSTER"
  if [ ! -d "$CLUSTER" ]; then
    ./get "$CLUSTER"
  fi
  pushd "$CLUSTER" > /dev/null || exit
  git reset --hard
  git checkout main
  git pull
  git checkout -B sumo-saml-cutover
  fix_codeowners "$CLUSTER"

  popd > /dev/null || exit
  if [[ "${CLUSTER}" == "i02" ]]; then
    break
  fi
  continue

  break
  git commit -m "Auto-update generate-wiki-links"
  git push -u origin sumo-saml-cutover
  gh pr create --title "Update workflows" --body "This is an automated PR created to update generate-wiki-links" | tee -a ../PRs
  git checkout main
  popd > /dev/null || exit
done
