#!/usr/bin/env bash
# vi: set noet :
set -euo pipefail
IFS=$'\n\t'

# File paths generated by this script:
#   outputs/$github_username/$year/standup-issues_${standup_repo_owner}_${standup_repo_name}.txt
#   outputs/$github_username/$year/standup/$issue_id.json
#   outputs/$github_username/$year/involved-issues.json
#   outputs/$github_username/$year/involved-issues/${repo_owner}_${repo_name}_${issue_num}.json
#   outputs/$github_username/$year/involved-prs.json
#   outputs/$github_username/$year/involved-prs/${repo_owner}_${repo_name}_${pr_num}.json

# Cleanup trap to remove temp files on exit
cleanup() {
  true
}
trap cleanup EXIT

# Color definitions for logging
red="$(tput setaf 1)"
green="$(tput setaf 2)"
yellow="$(tput setaf 3)"
cyan="$(tput setaf 6)"
white="$(tput setaf 7)"
gray="$(tput dim)$(tput setaf 7)"
magenta="$(tput setaf 5)"
reset="$(tput sgr0)"

# Logging functions with color support
custom_log() {
    local prefix="$1"
    local postfix="$2"
    shift 2
    local epoch="$(date +%s)"
    if [[ -p /dev/stdin && "$#" -eq 0 ]]; then
        while IFS= read -r line || [ -n "$line" ]; do
            >&2 echo -e "${epoch} ${prefix}${line}${postfix}"
        done
    else
        >&2 echo -e "${epoch} ${prefix}$*${postfix}"
    fi
}
plain() { custom_log "" "" "$@"; }
info() { custom_log "[i] " "" "$@"; }
debug() { custom_log "[${gray}D${reset}]${gray} " "${reset}" "$@"; }
pass() { custom_log "[${green}✔${reset}]${green} " "${reset}" "$@"; }
warn() { custom_log "[${magenta}!${reset}]${magenta} " "${reset}" "$@"; }
fail() { custom_log "[${red}✘${reset}]${red} " "${reset}" "$@"; }

# Configuration: Set sensible defaults for optional parameters.
# Only repo, username, and label are required - everything else
# adapts to your environment.
year="$(date +%Y)"
repo=""
github_username=""
issue_label=""
issue_limit=300
sed_command="sed"

# Parse command-line flags to override defaults
while getopts "y:r:u:l:i:p:s:" opt; do
  case "$opt" in
    y) year="$OPTARG" ;;
    r) repo="$OPTARG" ;;
    u) github_username="$OPTARG" ;;
    l) issue_label="$OPTARG" ;;
    i) issue_limit="$OPTARG" ;;
    *) exit 1 ;;
  esac
done

# Output ISO timestamp at script start
>&2 echo "START: $(date -Iseconds)"

# Validation: Ensure the three critical parameters are provided
if [[ -z "$repo" ]]; then
  fail "Error: -r repo required (format: owner/repo)"
  exit 1
fi
if [[ -z "$github_username" ]]; then
  fail "Error: -u github_username required"
  exit 1
fi
if [[ -z "$issue_label" ]]; then
  fail "Error: -l issue_label required"
  exit 1
fi

# Sed compatibility: Detect if we need GNU sed for in-place editing.
# macOS users may have installed GNU sed as 'gsed' or symlinked as
# 'sed'. We test for GNU sed support and fail early if unavailable.
if [[ "$sed_command" == "sed" ]]; then
  # Check if this sed supports GNU-style in-place editing
  if ! sed --version 2>&1 | grep -q "GNU"; then
    # Not GNU sed - check if gsed is available
    if command -v gsed &> /dev/null; then
      info "Using gsed instead of sed for GNU compatibility"
      sed_command="gsed"
    else
      fail "Error: GNU sed required. Install with: brew install gnu-sed"
      fail "Or specify sed command with: -s gsed"
      exit 1
    fi
  fi
elif [[ "$sed_command" == "gsed" ]]; then
  # User explicitly requested gsed - verify it exists
  if ! command -v gsed &> /dev/null; then
    fail "Error: gsed not found. Install with: brew install gnu-sed"
    exit 1
  fi
fi

# Rate limit management: Check GitHub API rate limit and sleep
# if approaching 80% usage to avoid hitting the limit.
check_rate_limit() {
  local limit remaining reset used

  # Fetch rate limit info from GitHub API
  local rate_info="$(gh api rate_limit 2>/dev/null || echo '{}')"

  limit="$(echo "$rate_info" | jq -r '.resources.core.limit // 5000')"
  remaining="$(echo "$rate_info" | jq -r '.resources.core.remaining // 5000')"
  reset="$(echo "$rate_info" | jq -r '.resources.core.reset // 0')"
  used="$(echo "$rate_info" | jq -r '.resources.core.used // 0')"

  # Calculate usage percentage
  local usage_pct=0
  if [[ "$limit" -gt 0 ]]; then
    usage_pct=$((used * 100 / limit))
  fi

  # If we're over 80% usage, sleep until reset
  if [[ "$usage_pct" -ge 80 ]]; then
    local now="$(date +%s)"
    local sleep_seconds=$((reset - now + 60))  # Add 60s buffer

    if [[ "$sleep_seconds" -gt 0 ]]; then
      local reset_time="$(date -d "@$reset" '+%Y-%m-%d %H:%M:%S' 2>/dev/null || date -r "$reset" '+%Y-%m-%d %H:%M:%S' 2>/dev/null || echo "unknown")"
      warn "Rate limit at ${usage_pct}% (${remaining}/${limit} remaining)"
      warn "Sleeping ${sleep_seconds}s until reset at ${reset_time}..."
      sleep "$sleep_seconds"
      pass "Rate limit reset, resuming..."
    fi
  fi
}

# Global path variables derived from configuration
year_dir="outputs/$github_username/$year"
standup_dir="$year_dir/standup"
standup_repo_owner="$(echo "$repo" | cut -d/ -f1)"
standup_repo_name="$(echo "$repo" | cut -d/ -f2)"
standup_issues_list="$year_dir/standup-issues_${standup_repo_owner}_${standup_repo_name}.txt"
org="$(echo "$repo" | cut -d/ -f1)"
involved_cache="$year_dir/involved-issues.json"
involved_issues_dir="$year_dir/involved-issues"
involved_prs_cache="$year_dir/involved-prs.json"
involved_prs_dir="$year_dir/involved-prs"


# Setup: Create user-specific output directory for organizing
# multiple users' data
mkdir -p "$standup_dir"

# Cleanup stale temp files from previous crashed runs
find "$year_dir" -maxdepth 1 -name "temp-issues-*.txt" -type f -delete 2>/dev/null || true

# Phase 1: Discover all relevant standup issues from the repository.
# Caches results to avoid repeated API calls when re-running.
if [[ ! -f "$standup_issues_list" ]]; then
  info "Fetching standup issue list from $repo..."
  gh \
    -R "$repo" issue list \
    --state all \
    --limit "$issue_limit" \
    --label "$issue_label" \
    --search "$year" \
    > "$standup_issues_list"
  pass "Found $(wc -l < "$standup_issues_list") standup issues"
else
  info "Using cached standup issue list ($(wc -l < "$standup_issues_list") issues)"
fi

# Phase 1b: Discover involved issues (assigned or authored) from org.
# Queries GitHub for issues where user was assigned or authored,
# filtering by created/closed dates. Caches results to avoid
# repeated API calls.
if [[ ! -f "$involved_cache" ]]; then
  info "Fetching involved issues (assigned/authored) from org: $org..."

  # Fetch 4 queries: assigned+created, assigned+closed, author+created, author+closed
  # Combine and deduplicate by URL
  {
    gh search issues --assignee "$github_username" --owner "$org" --created "$year-01-01..$year-12-31" --limit 1000 --json number,title,url,createdAt,closedAt,repository,state,body 2>/dev/null || echo "[]"
    gh search issues --assignee "$github_username" --owner "$org" --closed "$year-01-01..$year-12-31" --limit 1000 --json number,title,url,createdAt,closedAt,repository,state,body 2>/dev/null || echo "[]"
    gh search issues --author "$github_username" --owner "$org" --created "$year-01-01..$year-12-31" --limit 1000 --json number,title,url,createdAt,closedAt,repository,state,body 2>/dev/null || echo "[]"
    gh search issues --author "$github_username" --owner "$org" --closed "$year-01-01..$year-12-31" --limit 1000 --json number,title,url,createdAt,closedAt,repository,state,body 2>/dev/null || echo "[]"
  } | jq -s 'add | unique_by(.url)' > "$involved_cache"

  pass "Found $(jq 'length' "$involved_cache") involved issues"
else
  info "Using cached involved issues ($(jq 'length' "$involved_cache") issues)"
fi

# Phase 1c: Discover involved PRs (assigned or authored) from org.
# Queries GitHub for PRs where user was assigned or authored,
# filtering by created/closed dates. Caches results to avoid
# repeated API calls.
if [[ ! -f "$involved_prs_cache" ]]; then
  info "Fetching involved PRs (assigned/authored) from org: $org..."

  # Fetch 4 queries: assigned+created, assigned+closed, author+created, author+closed
  # Combine and deduplicate by URL
  {
    gh search prs --assignee "$github_username" --owner "$org" --created "$year-01-01..$year-12-31" --limit 1000 --json number,title,url,createdAt,closedAt,repository,state,body 2>/dev/null || echo "[]"
    gh search prs --assignee "$github_username" --owner "$org" --closed "$year-01-01..$year-12-31" --limit 1000 --json number,title,url,createdAt,closedAt,repository,state,body 2>/dev/null || echo "[]"
    gh search prs --author "$github_username" --owner "$org" --created "$year-01-01..$year-12-31" --limit 1000 --json number,title,url,createdAt,closedAt,repository,state,body 2>/dev/null || echo "[]"
    gh search prs --author "$github_username" --owner "$org" --closed "$year-01-01..$year-12-31" --limit 1000 --json number,title,url,createdAt,closedAt,repository,state,body 2>/dev/null || echo "[]"
  } | jq -s 'add | unique_by(.url)' > "$involved_prs_cache"

  pass "Found $(jq 'length' "$involved_prs_cache") involved PRs"
else
  info "Using cached involved PRs ($(jq 'length' "$involved_prs_cache") PRs)"
fi

exit 0

# Phase 2: Download detailed data for standup issues including all
# comments. Skips already-downloaded issues to enable incremental
# updates and avoid rate limits.
check_rate_limit
downloaded=0
skipped=0

# Process directly from file
iteration=0
while read -r issue_id _rest; do
  iteration=$((iteration + 1))

  # Progress indicator every 20 issues
  if [[ $((iteration % 20)) -eq 0 ]]; then
    info "Processed $iteration standup issues so far (downloaded: $downloaded, skipped: $skipped)"
  fi

  if [[ -z "$issue_id" ]]; then
    continue
  fi

  standup_json="$standup_dir/$issue_id.json"
  if [[ -f "$standup_json" ]]; then
    skipped=$((skipped + 1))
    continue
  fi

  # Check rate limit every 10 downloads
  if [[ $((downloaded % 10)) -eq 0 && "$downloaded" -gt 0 ]]; then
    check_rate_limit
  fi

  debug "Downloading standup issue $issue_id..."
  downloaded=$((downloaded + 1))
  gh -R "$repo" issue view "${issue_id}" \
    --comments \
    --json comments \
    --json title \
    > "$standup_json"
done < "$standup_issues_list"
pass "Standup issues - Downloaded: $downloaded, Skipped (cached): $skipped"

# Phase 2b: Download involved issue details and determine participation type.
# Stores in separate directory with repo-namespaced filenames.
mkdir -p "$involved_issues_dir"

info "Processing involved issues..."
check_rate_limit
involved_downloaded=0
involved_skipped=0

while read -r issue_json; do
  # Extract repo owner and name from URL (more reliable than repository object)
  issue_url="$(echo "$issue_json" | jq -r '.url')"
  repo_owner="$(echo "$issue_url" | cut -d'/' -f4)"
  repo_name="$(echo "$issue_url" | cut -d'/' -f5)"
  issue_num="$(echo "$issue_json" | jq -r '.number')"
  cache_file="$involved_issues_dir/${repo_owner}_${repo_name}_${issue_num}.json"

  if [[ -f "$cache_file" ]]; then
    involved_skipped=$((involved_skipped + 1))
    continue
  fi

  # Check rate limit every 10 downloads
  if [[ $((involved_downloaded % 10)) -eq 0 && "$involved_downloaded" -gt 0 ]]; then
    check_rate_limit
  fi

  debug "Downloading involved issue $repo_owner/$repo_name#$issue_num..."
  involved_downloaded=$((involved_downloaded + 1))

  # Fetch full issue details to determine participation type
  full_issue="$(gh issue view "$issue_num" --repo "$repo_owner/$repo_name" --json number,title,url,createdAt,closedAt,state,body,author,assignees 2>/dev/null || echo '{}')"

  # Skip if fetch failed (empty object or missing required fields)
  if [[ "$(echo "$full_issue" | jq -r '.number // empty')" == "" ]]; then
    debug "Skipping $repo_owner/$repo_name#$issue_num (fetch failed)"
    involved_downloaded=$((involved_downloaded - 1))
    continue
  fi

  # Determine participation type: Assigned, Author, or both
  is_author="$(echo "$full_issue" | jq -r --arg user "$github_username" '.author.login == $user')"
  is_assigned="$(echo "$full_issue" | jq -r --arg user "$github_username" '[.assignees[].login] | contains([$user])')"

  if [[ "$is_author" == "true" && "$is_assigned" == "true" ]]; then
    participation="Assigned+Author"
  elif [[ "$is_author" == "true" ]]; then
    participation="Author"
  elif [[ "$is_assigned" == "true" ]]; then
    participation="Assigned"
  else
    participation="Involved"
  fi

  # Add participation type to JSON and save
  echo "$full_issue" | jq --arg part "$participation" '. + {participation: $part}' > "$cache_file"
done < <(jq -c '.[]' "$involved_cache")

pass "Involved issues - Downloaded: $involved_downloaded, Skipped (cached): $involved_skipped"

# Phase 2c: Download involved PR details and determine participation type.
# Stores in separate directory with repo-namespaced filenames.
mkdir -p "$involved_prs_dir"

info "Processing involved PRs..."
check_rate_limit
prs_downloaded=0
prs_skipped=0

while read -r pr_json; do
  # Extract repo owner and name from URL (more reliable than repository object)
  pr_url="$(echo "$pr_json" | jq -r '.url')"
  repo_owner="$(echo "$pr_url" | cut -d'/' -f4)"
  repo_name="$(echo "$pr_url" | cut -d'/' -f5)"
  pr_num="$(echo "$pr_json" | jq -r '.number')"
  cache_file="$involved_prs_dir/${repo_owner}_${repo_name}_${pr_num}.json"

  if [[ -f "$cache_file" ]]; then
    prs_skipped=$((prs_skipped + 1))
    continue
  fi

  # Check rate limit every 10 downloads
  if [[ $((prs_downloaded % 10)) -eq 0 && "$prs_downloaded" -gt 0 ]]; then
    check_rate_limit
  fi

  debug "Downloading involved PR $repo_owner/$repo_name#$pr_num..."
  prs_downloaded=$((prs_downloaded + 1))

  # Fetch full PR details to determine participation type
  full_pr="$(gh pr view "$pr_num" --repo "$repo_owner/$repo_name" --json number,title,url,createdAt,closedAt,state,body,author,assignees 2>/dev/null || echo '{}')"

  # Skip if fetch failed (empty object or missing required fields)
  if [[ "$(echo "$full_pr" | jq -r '.number // empty')" == "" ]]; then
    debug "Skipping $repo_owner/$repo_name#$pr_num (fetch failed)"
    prs_downloaded=$((prs_downloaded - 1))
    continue
  fi

  # Determine participation type: Assigned, Author, or both
  is_author="$(echo "$full_pr" | jq -r --arg user "$github_username" '.author.login == $user')"
  is_assigned="$(echo "$full_pr" | jq -r --arg user "$github_username" '[.assignees[].login] | contains([$user])')"

  if [[ "$is_author" == "true" && "$is_assigned" == "true" ]]; then
    participation="Assigned+Author"
  elif [[ "$is_author" == "true" ]]; then
    participation="Author"
  elif [[ "$is_assigned" == "true" ]]; then
    participation="Assigned"
  else
    participation="Involved"
  fi

  # Add participation type to JSON and save
  echo "$full_pr" | jq --arg part "$participation" '. + {participation: $part}' > "$cache_file"
done < <(jq -c '.[]' "$involved_prs_cache")

pass "Involved PRs - Downloaded: $prs_downloaded, Skipped (cached): $prs_skipped"

pass "Done! All data cached in $year_dir/"

# Output ISO timestamp at script end
>&2 echo "END: $(date -Iseconds)"
