# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-requiring-successful-dependent-jobs
# https://docs.github.com/en/actions/learn-github-actions/expressions#status-check-functions
name: Test Workflow

# Controls when the workflow will run
on:
  # All pushes to main, and all push/create activity on pull requests
  push:
    branches: [ "main" ]
  pull_request:
    branches:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - name: a condition
        run: true
  second:
    runs-on: ubuntu-latest
    needs: first
    if: success()
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - id: checkout
        name: Perform Checkout
        uses: actions/checkout@v3

      - id: action-non-default
        name: Action: Other branch
        if: |
          github.ref_name != 'main'
        run: echo "github.ref_name ${{ github.ref_name }}"

      - id: action-default
        name: Action: Main branch
        if: github.ref_name == 'main'
        run: |
          # Some alternatives for the branch
          echo "github.ref ${{ github.ref == 'refs/heads/main' }}"
          echo "env.GITHUB_REF_NAME ${{ env.GITHUB_REF_NAME }}"
  third:
    runs-on: ubuntu-latest
    needs: first
    steps:
      - name: bad
        run: false
  forth:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs: third
    if: always()
    steps:
      - id: ignored
        name: Action: Ignored
        if: failure()
        run: echo "ignored"

      - id: good
        name: Action: Handled
        if: success()
        run: echo "handled"

      - id: crash
        name: Action: Crash, but continue
        continue-on-error: true
        run: false

      - id: finalize
        name: Action: Finalize
        if: always()
        run: |
          echo "finalize and succeed"
          true

  fifth:
    runs-on: ubuntu-latest
    needs: third
    if: success()
    steps:
      - id: skip
        name: Action: Skipped
        run: echo "should be skipped"
