# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  first:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: a condition
        run: |
          true
  second:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: first
    if: success()

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v3
      # Runs a single command using the runners shell
      - name: NOTMAIN
        # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-requiring-successful-dependent-jobs
        # https://docs.github.com/en/actions/learn-github-actions/expressions#status-check-functions
        if: |
          github.ref_name != 'main'
        run: |
          echo "github.ref_name ${{ github.ref_name }}"

      # Runs a set of commands using the runners shell
      - name: MAIN
        # alternative: ${{ github.ref == 'refs/heads/main' }}
        if: github.ref_name == 'main'
        run: |
          echo "github.ref_name ${{ github.ref_name }}"
          echo "env.GITHUB_REF_NAME ${{ env.GITHUB_REF_NAME }}"
  third:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: first

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: bad
        run: |
          false
  forth:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: third
    if: always()

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: IGNORED
        if: failure()
        run: |
          echo "ignored"

      # Runs a set of commands using the runners shell
      - name: GOOD
        # alternative: ${{ github.ref == 'refs/heads/main' }}
        if: success()
        run: |
          echo "good outcome"

      - name: crash
        run: false

      - name: BAD
        if: failure()
        run: |
          echo "bad outcome"
