# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v3
      - name: bad
        run: |
          false
      # Runs a single command using the runners shell
      - name: Not main and success
        # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-requiring-successful-dependent-jobs
        # https://docs.github.com/en/actions/learn-github-actions/expressions#status-check-functions
        if: |
          ${{ success() }} &&
          ${{ github.ref_name != 'main' }}
        needs: bad
        run: |
          echo "success() ${{ success() }}"
          echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script (only on main)
        # alternative: ${{ github.ref == 'refs/heads/main' }}
        if: ${{ github.ref_name == 'main' }}
        run: |
          echo "github.ref_name ${{ github.ref_name }}"
          echo "env.GITHUB_REF_NAME ${{ env.GITHUB_REF_NAME }}"
